#!/usr/bin/python3

DOMAIN = "simple-pwgen"
PATH = "/usr/share/locale"

import os
import gettext
import additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=simple-pwgen -g
Icon=simple-pwgen
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;Utility;
StartupNotify=false
NotShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/simple-pwgen.desktop", prefix, _("Simple Password Generator"), _("Very simple Python3-based GUI application to generate random password."), suffix)

prefix = "[Desktop Entry]\n"

suffix = """Exec=simple-pwgen -g
Icon=simple-pwgen
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;Utility;
X-KDE-StartupNotify=false
OnlyShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/kde4/simple-pwgen.desktop", prefix, _("Simple Password Generator"), _("Very simple Python3-based GUI application to generate random password."), suffix, genericName=_("Simple Password Generator"))
